name: Compute
extends: Object
version: 0.3.0
main: ./dist/index.js

provider: ${inputs.provider}
runtime: ${inputs.runtime}
memory: ${inputs.memory}
timeout: ${inputs.timeout}
environment: ${inputs.environment}
tags: ${inputs.tags}

inputTypes:
  provider:
    type: Provider
  runtime:
    type: string
    required: false
  memory:
    type: string
    default: 1024
    required: false
  timeout:
    type: string
    default: 10
    required: false
  environment:
    type: object
    required: false
  tags:
    type: object
    required: false
