name: AwsLambdaCompute
extends: Compute
main: ./dist/index.js
version: 0.3.0
core: 0.3.x

description: "AWS Lambda Compute"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

provider: ${inputs.provider}
runtime: ${inputs.runtime}
memory: ${inputs.memory}
timeout: ${inputs.timeout}
evironment: ${inputs.evironment}
tags: ${inputs.tags}
role: ${inputs.role}
ufs: ${inputs.ufs}

inputTypes:
  provider:
    type: Provider
  runtime:
    type: string
    required: false
    default: nodejs
  memory:
    type: integer
    required: false
    default: 1024
  timeout:
    type: integer
    required: false
    default: 10
  environment:
    type: object
    required: false
  role:
    type: AwsIamRole
    required: false
  tags:
    type: object
    required: false
  ufs:
    type: boolean
    required: false
