name: RestApi
extends: Component

version: 0.3.0
core: 0.3.x
main: ./dist/index.js

description: "REST API type component."
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

provider: ${inputs.provider}
gateway: ${inputs.gateway}
apiName: ${inputs.apiName}
routes: ${inputs.routes}

inputTypes:
  provider:
    type: AwsProvider
    required: true
  gateway:
    type: string
    enum: [AwsApiGateway]
  apiName:
    type: string
    required: false
  routes:
    type: object
    required: true
