# you can directly use serverless v1 services and
# components will deploy the service as part of the
# components deployment

service: dynamic-html

app: myapp-dev
tenant: bneisler

provider:
  name: aws
  runtime: nodejs6.10

functions:
  landingPage:
    handler: handler.landingPage
    events:
      - http:
          method: get
          path: /{proxy+}
