name: AwsCloudWatchEventsRule
extends: Component
main: ./dist/index.js
version: 0.3.0

enabled: ${inputs.enabled}
lambda: ${inputs.lambda}
provider: ${inputs.provider}
schedule: ${inputs.schedule}

inputTypes:
  provider:
    type: AwsProvider
    required: true
  enabled:
    type: boolean
    required: false
    default: true
  lambda:
    type: AwsLambdaFunction
    required: true
  schedule:
    type: string
    required: true
