name: AwsApiGateway
extends: Component

version: 0.3.0
core: 0.3.x
main: ./dist/index.js

description: "Provision AWS API Gateway with serverless components."
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

provider: ${inputs.provider}
swaggerTemplate: ${inputs.swaggerTemplate}
stage: ${inputs.stage}

inputTypes:
  provider:
    type: AwsProvider
    required: true
    description: "The AWS provider the holds the AWS credentials and SDK instance"
  swaggerTemplate:
    type: object
    required: true
    description: The full swagger template for your API
  stage:
    type: string
    required: false
    default: dev
    description: The stage to deploy the Rest Api to

