name: Function
extends: Component
main: ./dist/index.js

version: 0.3.0
description: "A cloud agnostic Severless Function"

functionName: ${inputs.functionName}
functionDescription: ${inputs.functionDescription}
memory: ${inputs.memory}
timeout: ${inputs.timeout}
runtime: ${inputs.runtime}
code: ${inputs.code}
handler: ${inputs.handler}
compute: ${inputs.compute}
environment: ${inputs.environment}
tags: ${inputs.tags}
ufs: ${inputs.ufs}

inputTypes:
  functionName:
    type: string
    required: true
  compute:
    type: Compute
    required: true
  code:
    type: string
    required: true
    description: path to folder for code
  handler:
    type: string
    required: true
    description: property path for function
  description:
    type: string
    required: false
    default: Serverless Universal Function
  memory:
    type: integer
    required: false
    default: 1024
  timeout:
    type: integer
    required: false
    default: 10
  runtime:
    type: string
    description: common format across providers that is converted by provider code
  environment:
    type: Object
    required: false
  tags:
    type: Object
    required: false
  ufs:
    type: boolean
    description: opt in for universal function signature
    required: false
    default: false
