name: TwilioApplication
extends: Component
version: 0.3.0
main: ./dist/index.js

description: "Provision Twilio Applications with the Serverless Framework"
license: Apache-2.0
author: "Serverless, Inc. <hello@serverless.com> (https://serverless.com)"
repository: "github:serverless/components"

inputTypes:
  provider:
    type: TwilioProvider
    required: true
    description: "The Twilo provider the holds the Twilio credentials"
  friendlyName:
    type: string
    required: true
    description: "A human readable description of the new application. Maximum 64 characters."
  apiVersion:
    type: string
    required: false
    description: "Requests to this application's URLs will start a new TwiML session with this API version. Either 2010-04-01 or 2008-08-01. Defaults to your account's default API version."
  voiceUrl:
    type: string
    required: false
    description: "The URL that Twilio should request when somebody dials a phone number assigned to this application."
  voiceMethod:
    type: string
    required: false
    description: "The HTTP method that should be used to request the VoiceUrl. Must be either GET or POST. Defaults to POST."
  voiceFallbackUrl:
    type: string
    required: false
    description: "A URL that Twilio will request if an error occurs requesting or executing the TwiML at Url."
  voiceFallbackMethod:
    type: string
    required: false
    description: "The HTTP method that should be used to request the VoiceFallbackUrl. Either GET or POST. Defaults to POST."
  statusCallback:
    type: string
    required: false
    description: "The URL that Twilio will request to pass status parameters (such as call ended) to your application."
  statusCallbackMethod:
    type: string
    required: false
    description: "The HTTP method Twilio will use to make requests to the StatusCallback URL. Either GET or POST. Defaults to POST."
  voiceCallerIdLookup:
    type: boolean
    required: false
    description: "Do a lookup of a caller's name from the CNAM database and post it to your app. Either true or false. Defaults to false."
  smsUrl:
    type: string
    required: false
    description: "The URL that Twilio should request when somebody sends an SMS to a phone number assigned to this application."
  smsMethod:
    type: string
    required: false
    description: "The HTTP method Twilio will use when making requests to the SmsUrl. Either GET or POST."
  smsFallbackUrl:
    type: string
    required: false
    description: "The URL that Twilio will request if an error occurs retrieving or executing the TwiML from SmsUrl."
  smsFallbackMethod:
    type: string
    required: false
    description: "The HTTP method Twilio will use when requesting the above URL. Either GET or POST."
  smsStatusCallback:
    type: string
    required: false
    description: "The URL that Twilio will POST to when a message is sent via the /SMS/Messages endpoint if you specify the Sid of this application on an outgoing SMS request."
  messageStatusCallback:
    type: string
    required: false
    description: "Twilio will make a POST request to this URL to pass status parameters (such as sent or failed) to your application if you use the /Messages endpoint to send the message and specify this application's Sid as the ApplicationSid on an outgoing SMS request."

provider: ${inputs.provider}
friendlyName: ${inputs.friendlyName}
apiVersion: ${inputs.apiVersion}
voiceUrl: ${inputs.voiceUrl}
voiceMethod: ${inputs.voiceMethod}
voiceFallbackUrl: ${inputs.voiceFallbackUrl}
voiceFallbackMethod: ${inputs.voiceFallbackMethod}
statusCallback: ${inputs.statusCallback}
statusCallbackMethod: ${inputs.statusCallbackMethod}
voiceCallerIdLookup: ${inputs.voiceCallerIdLookup}
smsUrl: ${inputs.smsUrl}
smsMethod: ${inputs.smsMethod}
smsFallbackUrl: ${inputs.smsFallbackUrl}
smsFallbackMethod: ${inputs.smsFallbackMethod}
smsStatusCallback: ${inputs.smsStatusCallback}
messageStatusCallback: ${inputs.messageStatusCallback}
